# The interval in which the server status of connected servers is checked. Value in seconds
ping_interval: 5

# Servers which not to ping
server_blacklist:
  - example

# Servers that will get online notifications
servers_to_notify:
  - lobby

# Hovertext
hover_text: Click to join the server

# Server back online message. %s will be replaced by the servername
# You can use color codes as seen here:
# https://media.discordapp.net/attachments/536426242766012426/577538720954318879/Color_codes.png
online_message: "[>>] %s is now online. [Click to Connect]"